name: sliceop
channels:
  - conda-forge
  - defaults
dependencies:
  - cfgrib
  - pandas
  - matplotlib
  - requests
  - xarray
  - cdsapi
  - numpy
  - netcdf4
  - scikit-learn
  - dask
  - bottleneck
